[package]
name = "rust_practice"
version = "0.1.0"
authors = ["Colwyn Fritze-Moor <colwyn@colwyn.me>"]
edition = "2018"

[dependencies]
rand = "0.6.5"
sysinfo = "0.8.4"
regex = "1.1.6"
tui = "0.6.0"
termion = "1.5.2"
